/*
VENTANA O FORMULARIO PRINCIPAL DEL REGISTRO
 */
package proyectodeasistenciadeuniversitarios;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @author Franz Quispe, Kevin Salas, Rodrigo Escobar, Omar Senzano
 */
public class FormUniversitarios extends javax.swing.JFrame {
    ExportarDatos objDatosU;//u
    
    private String dirArchivo="Registro_Universitario.txt";//ANTES  archiUniversitario
    UNIVERSITARIO univ; //declara un objeto univ de la clase UNIVERSITARIO
        //declara un objeto vu de la clase VectordeUniversitarios
    vectordeUniversitarios vu=new vectordeUniversitarios(); 
        //  File archi;
    DefaultTableModel dtm=new DefaultTableModel();
    int clickTabla;
    
    
    public FormUniversitarios() {
        initComponents();
        this.setLocationRelativeTo(this);//IMPORTANTE, coloca el formulario al centro
        dtm.addColumn("          R.U.");
        dtm.addColumn("       Nombre");
        dtm.addColumn("       Apellidos");
        dtm.addColumn("       Genero");
        dtm.addColumn("       Cargo");
        dtm.addColumn("       Edad");//añadido        
        this.tablaUniversitarios.setModel(dtm);
        try{
             cargarArchivoUniversitario();
             listarUniversitarios();
        }catch(Exception ex){
            mensaje("Error al abrir el archivo de universitarios");
        };
    }
    
    public Image getIconImage()//IMPORTANTE, ES PARA CAMBIAR EL LOGO DEL PROGRAMA
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("ImagenesdelProyecto/icon.png"));
        return retValue;
    }    
    
    public void cargarArchivoUniversitario()
    {
       File archi=new File(dirArchivo);//crea un archivo archi
              
       if(!archi.exists())//si el archivo no existe entonces
       try {
          archi.createNewFile();
        } catch (IOException ex) {
          Logger.getLogger(FormUniversitarios.class.getName()).log(Level.SEVERE,null,ex);
        }
        else{
        try{
            FileReader fremp=new FileReader(dirArchivo); 
            BufferedReader br=new BufferedReader(fremp);
            String linea=null;
            //llevamos los datos del archivo al vector
            //lee la primera linea del archivo de texto
            linea=br.readLine(); 
            
            while(linea!=null)
            {
                //separar la cadena linea separado por el token ,
                StringTokenizer st=new StringTokenizer(linea,",");
                univ=new UNIVERSITARIO();
                
                int cod=Integer.parseInt(st.nextToken());
                //int ed=Integer.parseInt(st.nextToken());//añadido------
                univ.setCodigo(cod);
                univ.setNombre(st.nextToken());
                univ.setApellidos(st.nextToken());
                String x=st.nextToken();
                univ.setGenero(x.charAt(1));
                univ.setCargo(st.nextToken());
                univ.setEdad(cod);//añadido
                
                vu.agregarUniversitario(univ);
                
                linea=br.readLine(); 
            }
            br.close();
            
        }catch(Exception ex)
        {
            mensaje("error al cargar el archivo"+ex.getMessage());
        }
}}
    
    public void listarUniversitarios()
    {
        Object fila[]=new Object[dtm.getColumnCount()];
        
        for(int i=0;i<vu.cantidadUniversitario();i++)
        {
            univ=vu.obtenerUniversitario(i);
            fila[0]=univ.getCodigo();
            fila[1]=univ.getNombre();
            fila[2]=univ.getApellidos();
            fila[3]=univ.getGenero();
            fila[4]=univ.getCargo();
            fila[5]=univ.getEdad();//añadido
            dtm.addRow(fila);
        }
        tablaUniversitarios.setModel(dtm);
    }
        
    void mensaje(String msje)
      {
          JOptionPane.showMessageDialog(null,msje);
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbCargo = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        brMasculino = new javax.swing.JRadioButton();
        brFemenino = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUniversitarios = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnllevarAingreso = new javax.swing.JButton();
        btnllevarAsalida = new javax.swing.JButton();
        btnterminarPrograma = new javax.swing.JButton();
        btnHola = new javax.swing.JButton();
        btnexportarExcel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        btnEstadistica = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblBanner = new javax.swing.JLabel();
        panelIconos = new javax.swing.JPanel();
        lblCerrar = new javax.swing.JLabel();
        lblMaximizar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Universitario");
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 191));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("R.U.: ");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Apellidos:");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtApellidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("Cargo dentro la universidad:");

        cmbCargo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Director de Carrera", "Secrecetari@", "Docente", "Universitario", "Visitante" }));
        cmbCargo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 255, 255)));
        cmbCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel3.setBackground(new java.awt.Color(255, 255, 176));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 153, 255), 1, true), "Género", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18), new java.awt.Color(255, 153, 153))); // NOI18N

        brMasculino.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        brMasculino.setText("Masculino");
        brMasculino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        brFemenino.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        brFemenino.setText("Femenino");
        brFemenino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brMasculino)
                    .addComponent(brFemenino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brMasculino)
                .addGap(18, 18, 18)
                .addComponent(brFemenino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaUniversitarios.setBackground(new java.awt.Color(204, 255, 204));
        tablaUniversitarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaUniversitarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "R.U.", " Nombre", "  Apellidos", "Género", "Cargo", "Edad"
            }
        ));
        tablaUniversitarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaUniversitarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUniversitariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUniversitarios);

        btnGuardar.setBackground(new java.awt.Color(204, 255, 204));
        btnGuardar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 102, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(153, 255, 204));
        btnModificar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 102, 204));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(204, 204, 255));
        btnEliminar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 102, 204));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnllevarAingreso.setBackground(new java.awt.Color(255, 255, 255));
        btnllevarAingreso.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnllevarAingreso.setForeground(new java.awt.Color(0, 102, 102));
        btnllevarAingreso.setText("Ir a Registro de Ingreso");
        btnllevarAingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnllevarAingresoActionPerformed(evt);
            }
        });

        btnllevarAsalida.setBackground(new java.awt.Color(255, 255, 255));
        btnllevarAsalida.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnllevarAsalida.setForeground(new java.awt.Color(0, 102, 102));
        btnllevarAsalida.setText("Ir a Registro de Salida");
        btnllevarAsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnllevarAsalidaActionPerformed(evt);
            }
        });

        btnterminarPrograma.setBackground(new java.awt.Color(255, 255, 0));
        btnterminarPrograma.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnterminarPrograma.setForeground(new java.awt.Color(255, 0, 51));
        btnterminarPrograma.setText("Terminar el día");
        btnterminarPrograma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnterminarPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnterminarProgramaActionPerformed(evt);
            }
        });

        btnHola.setBackground(new java.awt.Color(255, 204, 153));
        btnHola.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnHola.setForeground(new java.awt.Color(0, 102, 204));
        btnHola.setText("Generar QR");
        btnHola.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        btnHola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHolaActionPerformed(evt);
            }
        });

        btnexportarExcel.setBackground(new java.awt.Color(0, 153, 153));
        btnexportarExcel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnexportarExcel.setForeground(new java.awt.Color(204, 204, 204));
        btnexportarExcel.setText("Exportar a Excel");
        btnexportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexportarExcelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Edad:");

        txtEdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnEstadistica.setBackground(new java.awt.Color(51, 255, 204));
        btnEstadistica.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnEstadistica.setForeground(new java.awt.Color(0, 51, 153));
        btnEstadistica.setText("Estadística");
        btnEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnllevarAingreso)
                        .addGap(108, 108, 108)
                        .addComponent(btnllevarAsalida))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btnterminarPrograma))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btnEstadistica)))
                .addGap(0, 124, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1))
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(btnModificar)
                                .addGap(35, 35, 35)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnHola)
                                .addGap(31, 31, 31)
                                .addComponent(btnexportarExcel))
                            .addComponent(jScrollPane1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar)
                        .addComponent(btnHola)
                        .addComponent(btnModificar)
                        .addComponent(btnexportarExcel)))
                .addGap(18, 18, 18)
                .addComponent(btnEstadistica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnllevarAingreso)
                    .addComponent(btnllevarAsalida))
                .addGap(29, 29, 29)
                .addComponent(btnterminarPrograma)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 720, 670));

        jPanel1.setBackground(new java.awt.Color(2, 104, 176));
        jPanel1.setForeground(new java.awt.Color(2, 104, 176));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 750, 720, 30));

        jPanel5.setBackground(new java.awt.Color(8, 71, 148));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBanner.setBackground(new java.awt.Color(8, 71, 148));
        lblBanner.setForeground(new java.awt.Color(8, 71, 148));
        lblBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdelProyecto/1.jpg"))); // NOI18N
        jPanel5.add(lblBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 0, 521, 80));

        panelIconos.setBackground(new java.awt.Color(0, 102, 102));
        panelIconos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelIconos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCerrar.setBackground(new java.awt.Color(0, 0, 0));
        lblCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdelProyecto/Cerrar.png"))); // NOI18N
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        panelIconos.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblMaximizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaximizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdelProyecto/Maximizar.png"))); // NOI18N
        lblMaximizar.setCursor(new java.awt.Cursor(java.awt.Cursor.N_RESIZE_CURSOR));
        lblMaximizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMaximizarMouseClicked(evt);
            }
        });
        panelIconos.add(lblMaximizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblMinimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdelProyecto/Minimizar.png"))); // NOI18N
        lblMinimizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        panelIconos.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        jPanel5.add(panelIconos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 60, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int leerCodigo()
    {
        try{
            String aux=txtCodigo.getText().trim();
            int codigo=Integer.parseInt(aux);
            return codigo;
        }catch(Exception u)
        {
            return -99;
        }
    }
    String leerNombre()
    {
        try{
            String nombre=txtNombre.getText().trim();
            return nombre;
        }catch(Exception u)
        {
            return null;
        }
    }
    String leerApellidos()
    {
        try{
        String apellidos=txtApellidos.getText().trim();
        return apellidos;
        }catch(Exception u){
        return null;
        }
    }
        
    void registrarUniversitario(File dirArchivo)
    {
        try{
            if(leerCodigo()==-99) mensaje("Debe ingresar un número entero");
            else if(leerNombre()==null)mensaje("Debe ingresar el nombre");
            else if(leerApellidos()==null)mensaje("Debe ingresar apellidos");
            else if(leerEdad()==-99) mensaje("Debe ingresar un número entero");
            else
            {
                char genero;
                String cargo;
                if(brMasculino.isSelected())
                    genero='M';
                else genero ='F';
                cargo=(String)cmbCargo.getSelectedItem();
                
                univ=new UNIVERSITARIO(leerCodigo(),leerNombre(),leerApellidos(),genero,cargo,leerEdad());
                if((vu.buscarCodigoUniversitario(univ.getCodigo()))!=-1)
                {
                    mensaje("Este codigo ya existe");
                }
                else{
                    vu.agregarUniversitario(univ);
                }
                grabarUniversitario();
                limpiar();
                listarUniversitarios();
            }
        }catch(Exception ex)
        {
            mensaje("Error al abrir el archivo");
        }
    }
    
    void grabarUniversitario()
    {
        FileWriter fw;
        PrintWriter pw;
        
        try{
            fw=new FileWriter(dirArchivo);
            pw=new PrintWriter(fw);
            for(int i=0;i<vu.cantidadUniversitario();i++)
            {
                univ=vu.obtenerUniversitario(i);
                System.out.println(univ.getGenero());
                pw.println(String.valueOf(univ.getCodigo())+", "+univ.getNombre()+
                        ", "+univ.getApellidos()+", "+
                        univ.getGenero()+", "+univ.getCargo()+", "+String.valueOf(univ.getEdad()));
            }
            pw.close();
        }
        catch (Exception ex)
        {
            mensaje("Error al grabar en el archivo");
        }
    }
    
    void limpiar()
    {
        limpiarTabla();
        txtCodigo.setText(null);
        txtNombre.setText(null);
        txtApellidos.setText(null);
        brMasculino.setSelected(true);
        cmbCargo.setSelectedIndex(0);
        txtEdad.setText(null);
        limpiarTabla(); 
    }
    
    void limpiarTabla()
    {
        for (int i = 0; i < tablaUniversitarios.getRowCount(); i++) {
           dtm.removeRow(i);
            i-=1;
         }
    }
    char leerGenero()
    {
        if(brMasculino.isSelected())
           return 'M';
        else return 'F';
    }
    String leerCargo()
    {
        return((String)cmbCargo.getSelectedItem());
    }
    
   int leerEdad()//añadido------------------------------------------------------------------
    {
        try{
            String aux=txtEdad.getText().trim();
            int edad=Integer.parseInt(aux);
            return edad;
        }catch(Exception e)
        {
            return -99;
        }
    }       
    void modificarUniversitario (File dirArch)
    {
        try{
            if(leerCodigo()==-99)mensaje("Ingresar codigo entero");
            else if(leerNombre()==null)mensaje("Ingresar el nombre");
            else if(leerApellidos()==null)mensaje("Ingresar apellidos");
            else
            {
                int codigo=vu.buscarCodigoUniversitario(leerCodigo());
                univ=new UNIVERSITARIO(leerCodigo(),leerNombre(),leerApellidos(),leerGenero(),leerCargo(),leerEdad());
                if (codigo==-1)
                    vu.agregarUniversitario(univ);
                else{
                    vu.modificarUniversitario(codigo, univ);
                }
                grabarUniversitario();
                limpiar();
                listarUniversitarios();
            }
        }catch(Exception ex){
            mensaje("Error al abrir el archiovo para modificar");
        }
    }
    
    void eliminarUniversitario ()
    {
        try
       {
           if(leerCodigo()==-99) mensaje("ingresar un codigo entero");
           else
           {
               int codigo=vu.buscarCodigoUniversitario(leerCodigo());
               if(codigo==-1)
               {
                   mensaje("El codigo no existe");
               }else {
                   int s=JOptionPane.showConfirmDialog(null,"Esta seguro de "
                           + "eliminar este universitario ","si/no",0);
                   if(s==0)
                   {
                       vu.eliminarUniversitario(codigo);
                       grabarUniversitario();
                       limpiar();
                       listarUniversitarios();
                   }
               }
           }
       }catch(Exception ex){
           mensaje("No se ha podido eliminar el registro");
       }
    }
        
        
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnllevarAingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnllevarAingresoActionPerformed
        FormIngresodeUniversitarios fiu=new FormIngresodeUniversitarios();
        this.dispose();//cierra el formulario Principal de Funciones, lo libera de la memoria
        fiu.setVisible(true);//mostrara el formulario del Factorial
    }//GEN-LAST:event_btnllevarAingresoActionPerformed

    private void btnllevarAsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnllevarAsalidaActionPerformed
        FormSalidadeUniversitarios fsu=new FormSalidadeUniversitarios();
        this.dispose();//cierra el formulario Principal de Funciones, lo libera de la memoria
        fsu.setVisible(true);//mostrara el formulario del Factorial
    }//GEN-LAST:event_btnllevarAsalidaActionPerformed

    private void btnterminarProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnterminarProgramaActionPerformed
        System.exit(0);//termina el programa.Importante
    }//GEN-LAST:event_btnterminarProgramaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        File dirarchi=new File(dirArchivo);
        this.registrarUniversitario(dirarchi);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        File archi=new File(dirArchivo);
        modificarUniversitario(archi);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarUniversitario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaUniversitariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUniversitariosMouseClicked
        clickTabla = tablaUniversitarios.rowAtPoint(evt.getPoint());

        int codigo = (int) tablaUniversitarios.getValueAt(clickTabla, 0);
        String nombre = "" + tablaUniversitarios.getValueAt(clickTabla, 1);
        String apellidos = ""+tablaUniversitarios.getValueAt(clickTabla, 2);
        char genero=(char)tablaUniversitarios.getValueAt(clickTabla,3);
        String cargo=""+tablaUniversitarios.getValueAt(clickTabla,4);
        cargo=cargo.trim();
        int edad = (int) tablaUniversitarios.getValueAt(clickTabla, 5);
      
        txtCodigo.setText(String.valueOf(codigo));
        txtNombre.setText(nombre);
        txtApellidos.setText(apellidos);
        if(genero=='M') brMasculino.setSelected(true);
        else brFemenino.setSelected(true);
        txtEdad.setText(String.valueOf(edad));
        
        for(int i=0; i<cmbCargo.getItemCount();i++)
            if(cargo.equals(cmbCargo.getItemAt(i))){
                 cmbCargo.setSelectedIndex(i);
                 break;}
        
    }//GEN-LAST:event_tablaUniversitariosMouseClicked

    private void btnHolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHolaActionPerformed
        frmPrincipal y=new frmPrincipal();
        y.setVisible(true);     
    }//GEN-LAST:event_btnHolaActionPerformed

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        System.exit(0);//termina el programa.Importante, como el Boton Terminar el dia
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblMaximizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizarMouseClicked
        if(evt.getButton()==java.awt.event.MouseEvent.BUTTON1)//IMPORTANTE,BUTTON1 es el click izquierdo del mouse
        {
            this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_lblMaximizarMouseClicked

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        if(evt.getButton()==java.awt.event.MouseEvent.BUTTON1)//IMPORTANTE,BUTTON1 es el click izquierdo del mouse
        {
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void btnexportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexportarExcelActionPerformed
        try {// ultimo agregado
           objDatosU = new ExportarDatos();//mandar llamar la clase exportar 
           objDatosU.exportarExcel(tablaUniversitarios);//mandamos llamar el metodo exportarExcel desde la clase ExportarDatos
        }catch(IOException ex){    
        }
    }//GEN-LAST:event_btnexportarExcelActionPerformed

    private void btnEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticaActionPerformed
        FormEstadistica fe=new FormEstadistica();
        this.dispose();//cierra el formulario Principal de Funciones, lo libera de la memoria
        fe.setVisible(true);//mostrara el formulario de la Potencia
    }//GEN-LAST:event_btnEstadisticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUniversitarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUniversitarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUniversitarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUniversitarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUniversitarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton brFemenino;
    private javax.swing.JRadioButton brMasculino;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEstadistica;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHola;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnexportarExcel;
    private javax.swing.JButton btnllevarAingreso;
    private javax.swing.JButton btnllevarAsalida;
    private javax.swing.JButton btnterminarPrograma;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMaximizar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JPanel panelIconos;
    public javax.swing.JTable tablaUniversitarios;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
