/*
    FORMULARIO QUE GENERA GRAFICO SECTORIAL O CIRCULAR
 */
package proyectodeasistenciadeuniversitarios;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 * @author Franz Quispe, Kevin Salas, Rodrigo Escobar, Omar Senzano
 */
public class FormCircular extends javax.swing.JFrame {

    public FormCircular() {
        initComponents();
        this.setLocationRelativeTo(this);//IMPORTANTE, coloca el formulario al centro
    }
    
    public Image getIconImage()//IMPORTANTE, ES PARA CAMBIAR EL LOGO DEL PROGRAMA
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("ImagenesdelProyecto/icon.png"));
        return retValue;
    }     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVideojuegos = new javax.swing.JLabel();
        lblDeportes = new javax.swing.JLabel();
        lblInternet = new javax.swing.JLabel();
        lblLibros = new javax.swing.JLabel();
        txtDirector = new javax.swing.JTextField();
        txtSecretarioa = new javax.swing.JTextField();
        txtDocente = new javax.swing.JTextField();
        txtUniversitario = new javax.swing.JTextField();
        btnGraficar = new javax.swing.JButton();
        panelCircular = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtVisitante = new javax.swing.JTextField();
        btnVolverEstadistica = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GRÁFICO SECTORIAL O CIRCULAR");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVideojuegos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblVideojuegos.setText("DIRECTOR DE CARRERA");
        getContentPane().add(lblVideojuegos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        lblDeportes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDeportes.setText("SECRETARIO/A");
        getContentPane().add(lblDeportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        lblInternet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblInternet.setText("DOCENTE");
        getContentPane().add(lblInternet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        lblLibros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLibros.setText("UNIVERSITARIO");
        getContentPane().add(lblLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        txtDirector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 50, -1));

        txtSecretarioa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtSecretarioa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, -1));

        txtDocente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocenteActionPerformed(evt);
            }
        });
        getContentPane().add(txtDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 50, -1));

        txtUniversitario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtUniversitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, -1));

        btnGraficar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnGraficar.setText("Gráfico Circular");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGraficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        panelCircular.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelCircularLayout = new javax.swing.GroupLayout(panelCircular);
        panelCircular.setLayout(panelCircularLayout);
        panelCircularLayout.setHorizontalGroup(
            panelCircularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCircularLayout.setVerticalGroup(
            panelCircularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        getContentPane().add(panelCircular, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 500, 300));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("VISITANTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        txtVisitante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txtVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 50, -1));

        btnVolverEstadistica.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnVolverEstadistica.setText("Volver a Estadística");
        btnVolverEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverEstadisticaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 690, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Castellar", 1, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CARGOS DENTRO DE LA UNIVERSIDAD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        //Convertiremos a entero lo que esta en los campos de texto txt
        int n1 = Integer.parseInt(txtDirector.getText());
        int n2 = Integer.parseInt(txtSecretarioa.getText());
        int n3 = Integer.parseInt(txtDocente.getText());
        int n4 = Integer.parseInt(txtUniversitario.getText());
        int n5 = Integer.parseInt(txtVisitante.getText());
        
        DefaultPieDataset datos = new DefaultPieDataset();
        datos.setValue("Director de Carrera",n1);
        datos.setValue("Secretario/a",n2);
        datos.setValue("Docentes",n3);
        datos.setValue("Universitarios",n4);
        datos.setValue("Visitantes", n5);
        
        //creamos el Objeto de tipo JfreeChart
        JFreeChart grafico_circular = ChartFactory.createPieChart(
        "CARGOS DENTRO LA UNIVERSIDAD",        //nombre de grafico
        datos,        //datos
        true,        //nombre de las categorias
        true,        //herramientas
        false        //generacion de URL
        );
        //creamos otro Objeto tipo panel
        ChartPanel panel = new ChartPanel(grafico_circular);//creamos el panel y le asignamos el grafico_circular
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(500,300));//ancho y largo
        panelCircular.setLayout(new BorderLayout());
        panelCircular.add(panel,BorderLayout.NORTH);
        
        pack();
        repaint();           
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnVolverEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverEstadisticaActionPerformed
        FormEstadistica fEst=new FormEstadistica();//creamos una instancia fm de la clase, para hacer una referencia de otro formulario
        this.dispose();//libera la memoria y cierra el formulario actual
        fEst.setVisible(true);//lo hara visible setVisible(true)
    }//GEN-LAST:event_btnVolverEstadisticaActionPerformed

    private void txtDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCircular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCircular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCircular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCircular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCircular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnVolverEstadistica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDeportes;
    private javax.swing.JLabel lblInternet;
    private javax.swing.JLabel lblLibros;
    private javax.swing.JLabel lblVideojuegos;
    private javax.swing.JPanel panelCircular;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtDocente;
    private javax.swing.JTextField txtSecretarioa;
    private javax.swing.JTextField txtUniversitario;
    private javax.swing.JTextField txtVisitante;
    // End of variables declaration//GEN-END:variables
}
